# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracker_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.medianFilterCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.medianFilterCheckbox.setObjectName("medianFilterCheckbox")
        self.gridLayout_4.addWidget(self.medianFilterCheckbox, 7, 0, 1, 1)
        self.kernelValueLabel = QtWidgets.QLabel(self.groupBox_2)
        self.kernelValueLabel.setObjectName("kernelValueLabel")
        self.gridLayout_4.addWidget(self.kernelValueLabel, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 4, 1, 1)
        self.highPass_le = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highPass_le.sizePolicy().hasHeightForWidth())
        self.highPass_le.setSizePolicy(sizePolicy)
        self.highPass_le.setMaximumSize(QtCore.QSize(60, 16777215))
        self.highPass_le.setObjectName("highPass_le")
        self.gridLayout_4.addWidget(self.highPass_le, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 9, 4, 1, 1)
        self.gaussValueLabel = QtWidgets.QLabel(self.groupBox_2)
        self.gaussValueLabel.setObjectName("gaussValueLabel")
        self.gridLayout_4.addWidget(self.gaussValueLabel, 4, 3, 1, 1)
        self.gaussCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.gaussCheckBox.setChecked(True)
        self.gaussCheckBox.setObjectName("gaussCheckBox")
        self.gridLayout_4.addWidget(self.gaussCheckBox, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 7, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 3, 1, 1)
        self.medianValueLabel = QtWidgets.QLabel(self.groupBox_2)
        self.medianValueLabel.setObjectName("medianValueLabel")
        self.gridLayout_4.addWidget(self.medianValueLabel, 7, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 1, 1, 1)
        self.lowPass_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.lowPass_cb.setChecked(True)
        self.lowPass_cb.setObjectName("lowPass_cb")
        self.gridLayout_4.addWidget(self.lowPass_cb, 0, 0, 1, 1)
        self.highPass_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.highPass_cb.setChecked(True)
        self.highPass_cb.setObjectName("highPass_cb")
        self.gridLayout_4.addWidget(self.highPass_cb, 0, 1, 1, 1)
        self.lowPass_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.lowPass_le.setMinimumSize(QtCore.QSize(0, 0))
        self.lowPass_le.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lowPass_le.setObjectName("lowPass_le")
        self.gridLayout_4.addWidget(self.lowPass_le, 1, 0, 1, 1)
        self.medianSlider = QtWidgets.QSlider(self.groupBox_2)
        self.medianSlider.setOrientation(QtCore.Qt.Horizontal)
        self.medianSlider.setObjectName("medianSlider")
        self.gridLayout_4.addWidget(self.medianSlider, 7, 1, 1, 1)
        self.gaussSlider = QtWidgets.QSlider(self.groupBox_2)
        self.gaussSlider.setProperty("value", 6)
        self.gaussSlider.setSliderPosition(6)
        self.gaussSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussSlider.setInvertedControls(True)
        self.gaussSlider.setObjectName("gaussSlider")
        self.gridLayout_4.addWidget(self.gaussSlider, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_6.raise_()
        self.gaussCheckBox.raise_()
        self.medianFilterCheckbox.raise_()
        self.gaussValueLabel.raise_()
        self.kernelValueLabel.raise_()
        self.medianValueLabel.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.highPass_le.raise_()
        self.lowPass_cb.raise_()
        self.highPass_cb.raise_()
        self.label_11.raise_()
        self.gaussSlider.raise_()
        self.medianSlider.raise_()
        self.lowPass_le.raise_()
        self.label_2.raise_()
        self.gridLayout_8.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.trkTrack_B = QtWidgets.QPushButton(self.groupBox_7)
        self.trkTrack_B.setCheckable(True)
        self.trkTrack_B.setObjectName("trkTrack_B")
        self.gridLayout_8.addWidget(self.trkTrack_B, 1, 0, 1, 1)
        self.saveTrack_b = QtWidgets.QPushButton(self.groupBox_7)
        self.saveTrack_b.setObjectName("saveTrack_b")
        self.gridLayout_8.addWidget(self.saveTrack_b, 2, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox_7)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.chooseProjectPath_b = QtWidgets.QPushButton(self.groupBox_12)
        self.chooseProjectPath_b.setObjectName("chooseProjectPath_b")
        self.gridLayout_22.addWidget(self.chooseProjectPath_b, 0, 0, 1, 2)
        self.active_path_label = QtWidgets.QLabel(self.groupBox_12)
        self.active_path_label.setObjectName("active_path_label")
        self.gridLayout_22.addWidget(self.active_path_label, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        self.label_20.setObjectName("label_20")
        self.gridLayout_22.addWidget(self.label_20, 5, 0, 1, 1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_12)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.trkPreview_B = QtWidgets.QPushButton(self.groupBox)
        self.trkPreview_B.setObjectName("trkPreview_B")
        self.gridLayout_9.addWidget(self.trkPreview_B, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 3, 0, 1, 1)
        self.trkLoad_B = QtWidgets.QPushButton(self.groupBox)
        self.trkLoad_B.setObjectName("trkLoad_B")
        self.gridLayout_9.addWidget(self.trkLoad_B, 0, 0, 2, 1)
        self.pathLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pathLabel.setScaledContents(False)
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout_9.addWidget(self.pathLabel, 4, 0, 1, 1)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tab_6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_19)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_7.setObjectName("formLayout_7")
        self.selBackgroundVid_b = QtWidgets.QPushButton(self.groupBox_8)
        self.selBackgroundVid_b.setEnabled(True)
        self.selBackgroundVid_b.setObjectName("selBackgroundVid_b")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.selBackgroundVid_b)
        self.choose_background_b = QtWidgets.QPushButton(self.groupBox_8)
        self.choose_background_b.setEnabled(True)
        self.choose_background_b.setObjectName("choose_background_b")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.choose_background_b)
        self.gridLayout_6.addWidget(self.groupBox_8, 5, 0, 1, 1)
        self.firstFrame_rb = QtWidgets.QRadioButton(self.frame_5)
        self.firstFrame_rb.setChecked(True)
        self.firstFrame_rb.setObjectName("firstFrame_rb")
        self.gridLayout_6.addWidget(self.firstFrame_rb, 0, 0, 1, 1)
        self.specifyBackground_rb = QtWidgets.QRadioButton(self.frame_5)
        self.specifyBackground_rb.setObjectName("specifyBackground_rb")
        self.gridLayout_6.addWidget(self.specifyBackground_rb, 2, 0, 1, 1)
        self.mog_rb = QtWidgets.QRadioButton(self.frame_5)
        self.mog_rb.setChecked(False)
        self.mog_rb.setObjectName("mog_rb")
        self.gridLayout_6.addWidget(self.mog_rb, 1, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_5, 0, 0, 1, 1)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_19)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.formLayout_5 = QtWidgets.QFormLayout(self.tab_8)
        self.formLayout_5.setObjectName("formLayout_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.enableBlock_b = QtWidgets.QPushButton(self.groupBox_6)
        self.enableBlock_b.setObjectName("enableBlock_b")
        self.gridLayout_18.addWidget(self.enableBlock_b, 2, 2, 1, 1)
        self.blockOutRegions_cb = QtWidgets.QCheckBox(self.groupBox_6)
        self.blockOutRegions_cb.setEnabled(True)
        self.blockOutRegions_cb.setChecked(True)
        self.blockOutRegions_cb.setObjectName("blockOutRegions_cb")
        self.gridLayout_18.addWidget(self.blockOutRegions_cb, 0, 0, 1, 1)
        self.blockRegions_lw = QtWidgets.QListWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockRegions_lw.sizePolicy().hasHeightForWidth())
        self.blockRegions_lw.setSizePolicy(sizePolicy)
        self.blockRegions_lw.setObjectName("blockRegions_lw")
        self.gridLayout_18.addWidget(self.blockRegions_lw, 1, 0, 4, 1)
        self.disableBlock_b = QtWidgets.QPushButton(self.groupBox_6)
        self.disableBlock_b.setObjectName("disableBlock_b")
        self.gridLayout_18.addWidget(self.disableBlock_b, 2, 1, 1, 1)
        self.addBlock_b = QtWidgets.QPushButton(self.groupBox_6)
        self.addBlock_b.setObjectName("addBlock_b")
        self.gridLayout_18.addWidget(self.addBlock_b, 1, 1, 1, 1)
        self.deleteBlock_b = QtWidgets.QPushButton(self.groupBox_6)
        self.deleteBlock_b.setObjectName("deleteBlock_b")
        self.gridLayout_18.addWidget(self.deleteBlock_b, 1, 2, 1, 1)
        self.saveBlock_b = QtWidgets.QPushButton(self.groupBox_6)
        self.saveBlock_b.setObjectName("saveBlock_b")
        self.gridLayout_18.addWidget(self.saveBlock_b, 4, 2, 1, 1)
        self.loadBlock_b = QtWidgets.QPushButton(self.groupBox_6)
        self.loadBlock_b.setObjectName("loadBlock_b")
        self.gridLayout_18.addWidget(self.loadBlock_b, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_18.addWidget(self.line, 3, 1, 1, 2)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_6)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.formLayout_6 = QtWidgets.QFormLayout(self.tab_9)
        self.formLayout_6.setObjectName("formLayout_6")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_20)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.start_sb = QtWidgets.QSpinBox(self.frame_3)
        self.start_sb.setMaximum(999998)
        self.start_sb.setObjectName("start_sb")
        self.gridLayout_12.addWidget(self.start_sb, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.stop_sb = QtWidgets.QSpinBox(self.frame_3)
        self.stop_sb.setMaximum(1000000)
        self.stop_sb.setObjectName("stop_sb")
        self.gridLayout_12.addWidget(self.stop_sb, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.selectStartStop_b = QtWidgets.QPushButton(self.groupBox_20)
        self.selectStartStop_b.setObjectName("selectStartStop_b")
        self.gridLayout.addWidget(self.selectStartStop_b, 0, 0, 1, 1)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_20)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_7, 0, 1, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.track_TE = QtWidgets.QTextBrowser(self.groupBox_4)
        self.track_TE.setMinimumSize(QtCore.QSize(200, 0))
        self.track_TE.setObjectName("track_TE")
        self.verticalLayout.addWidget(self.track_TE)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setEnabled(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_9)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.reorder_b = QtWidgets.QPushButton(self.groupBox_3)
        self.reorder_b.setObjectName("reorder_b")
        self.gridLayout_3.addWidget(self.reorder_b, 3, 1, 1, 1)
        self.deleteTrack_b = QtWidgets.QPushButton(self.groupBox_3)
        self.deleteTrack_b.setObjectName("deleteTrack_b")
        self.gridLayout_3.addWidget(self.deleteTrack_b, 1, 1, 1, 1)
        self.tracks_lw = QtWidgets.QListWidget(self.groupBox_3)
        self.tracks_lw.setObjectName("tracks_lw")
        self.gridLayout_3.addWidget(self.tracks_lw, 0, 0, 8, 1)
        self.show2Dplot_B = QtWidgets.QCheckBox(self.groupBox_3)
        self.show2Dplot_B.setChecked(False)
        self.show2Dplot_B.setObjectName("show2Dplot_B")
        self.gridLayout_3.addWidget(self.show2Dplot_B, 4, 1, 1, 1)
        self.loadTracks_b = QtWidgets.QPushButton(self.groupBox_3)
        self.loadTracks_b.setObjectName("loadTracks_b")
        self.gridLayout_3.addWidget(self.loadTracks_b, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 1, 1, 1)
        self.delAllTracks_b = QtWidgets.QPushButton(self.groupBox_3)
        self.delAllTracks_b.setObjectName("delAllTracks_b")
        self.gridLayout_3.addWidget(self.delAllTracks_b, 2, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ppBlank_B = QtWidgets.QPushButton(self.groupBox_11)
        self.ppBlank_B.setObjectName("ppBlank_B")
        self.verticalLayout_3.addWidget(self.ppBlank_B)
        self.interpolate_b = QtWidgets.QPushButton(self.groupBox_11)
        self.interpolate_b.setObjectName("interpolate_b")
        self.verticalLayout_3.addWidget(self.interpolate_b)
        self.ppUndo_B = QtWidgets.QPushButton(self.groupBox_11)
        self.ppUndo_B.setObjectName("ppUndo_B")
        self.verticalLayout_3.addWidget(self.ppUndo_B)
        self.saveTrackEdits_b = QtWidgets.QPushButton(self.groupBox_11)
        self.saveTrackEdits_b.setObjectName("saveTrackEdits_b")
        self.verticalLayout_3.addWidget(self.saveTrackEdits_b)
        self.gridLayout_3.addWidget(self.groupBox_11, 6, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.groupBox_9)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.newCalibration_b = QtWidgets.QPushButton(self.tab_4)
        self.newCalibration_b.setObjectName("newCalibration_b")
        self.verticalLayout_5.addWidget(self.newCalibration_b)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget_5.addTab(self.tab_4, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.formLayout_8 = QtWidgets.QFormLayout(self.tab_11)
        self.formLayout_8.setObjectName("formLayout_8")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.loadCal_b = QtWidgets.QPushButton(self.groupBox_10)
        self.loadCal_b.setObjectName("loadCal_b")
        self.gridLayout_7.addWidget(self.loadCal_b, 0, 0, 1, 1)
        self.showCal_b = QtWidgets.QPushButton(self.groupBox_10)
        self.showCal_b.setObjectName("showCal_b")
        self.gridLayout_7.addWidget(self.showCal_b, 1, 0, 1, 1)
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_10)
        self.tabWidget_5.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.reconstruct_3D_b = QtWidgets.QPushButton(self.tab_12)
        self.reconstruct_3D_b.setObjectName("reconstruct_3D_b")
        self.gridLayout_2.addWidget(self.reconstruct_3D_b, 0, 0, 1, 1)
        self.save3DTrack_b = QtWidgets.QPushButton(self.tab_12)
        self.save3DTrack_b.setObjectName("save3DTrack_b")
        self.gridLayout_2.addWidget(self.save3DTrack_b, 2, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_23 = QtWidgets.QLabel(self.groupBox_13)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_13)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_13)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_13)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 0, 3, 1, 1)
        self.ymin_le = QtWidgets.QLineEdit(self.groupBox_13)
        self.ymin_le.setObjectName("ymin_le")
        self.gridLayout_11.addWidget(self.ymin_le, 3, 2, 1, 1)
        self.ymax_le = QtWidgets.QLineEdit(self.groupBox_13)
        self.ymax_le.setObjectName("ymax_le")
        self.gridLayout_11.addWidget(self.ymax_le, 3, 3, 1, 1)
        self.zmin_le = QtWidgets.QLineEdit(self.groupBox_13)
        self.zmin_le.setObjectName("zmin_le")
        self.gridLayout_11.addWidget(self.zmin_le, 4, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_13)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 0, 2, 1, 1)
        self.xmin_le = QtWidgets.QLineEdit(self.groupBox_13)
        self.xmin_le.setObjectName("xmin_le")
        self.gridLayout_11.addWidget(self.xmin_le, 1, 2, 1, 1)
        self.xmax_le = QtWidgets.QLineEdit(self.groupBox_13)
        self.xmax_le.setObjectName("xmax_le")
        self.gridLayout_11.addWidget(self.xmax_le, 1, 3, 1, 1)
        self.zmax_le = QtWidgets.QLineEdit(self.groupBox_13)
        self.zmax_le.setObjectName("zmax_le")
        self.gridLayout_11.addWidget(self.zmax_le, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_13)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 6, 2, 1, 1)
        self.plot3D_b = QtWidgets.QPushButton(self.groupBox_13)
        self.plot3D_b.setObjectName("plot3D_b")
        self.gridLayout_11.addWidget(self.plot3D_b, 5, 1, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox_13, 3, 0, 1, 1)
        self.show3Dcoords_b = QtWidgets.QPushButton(self.tab_12)
        self.show3Dcoords_b.setObjectName("show3Dcoords_b")
        self.gridLayout_2.addWidget(self.show3Dcoords_b, 1, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_12, "")
        self.verticalLayout_4.addWidget(self.tabWidget_5)
        self.gridLayout_14.addWidget(self.groupBox_9, 0, 0, 2, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pp_TV = QtWidgets.QTableView(self.groupBox_5)
        self.pp_TV.setMinimumSize(QtCore.QSize(300, 0))
        self.pp_TV.setObjectName("pp_TV")
        self.verticalLayout_2.addWidget(self.pp_TV)
        self.tableItem_l = QtWidgets.QLabel(self.groupBox_5)
        self.tableItem_l.setObjectName("tableItem_l")
        self.verticalLayout_2.addWidget(self.tableItem_l)
        self.gridLayout_14.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_13.addWidget(self.tabWidget, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(3)
        self.tabWidget_5.setCurrentIndex(0)
        self.specifyBackground_rb.toggled['bool'].connect(self.groupBox_8.setVisible)
        self.lowPass_cb.toggled['bool'].connect(self.lowPass_le.setVisible)
        self.lowPass_cb.toggled['bool'].connect(self.label_2.setVisible)
        self.highPass_cb.toggled['bool'].connect(self.highPass_le.setVisible)
        self.highPass_cb.toggled['bool'].connect(self.label_11.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setToolTip(_translate("MainWindow", "Video loading functions"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Tracking:"))
        self.groupBox_2.setToolTip(_translate("MainWindow", "Lower limit for detectable contour area in pixels"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Live video treatment:"))
        self.medianFilterCheckbox.setToolTip(_translate("MainWindow", "Removes fuzzy noise (slow)"))
        self.medianFilterCheckbox.setText(_translate("MainWindow", "Apply median filter"))
        self.kernelValueLabel.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "px"))
        self.highPass_le.setToolTip(_translate("MainWindow", "<html><head/><body><p>Before tracking, specify the highpass contour area threshold for detection. All contours with areas less than the specified threshold value will be discarded. Sometimes it is useful to track once with a low threshold value as a guess and then look at the tracking output to determine a better guess for a second pass through the tracking. Threshold pixel area defaults to 100 pixels.</p></body></html>"))
        self.highPass_le.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "px"))
        self.gaussValueLabel.setText(_translate("MainWindow", "6"))
        self.gaussCheckBox.setToolTip(_translate("MainWindow", "Smooth out image by applying a Gaussian filter."))
        self.gaussCheckBox.setText(_translate("MainWindow", "Use Guassian blur"))
        self.label.setText(_translate("MainWindow", "px"))
        self.medianValueLabel.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "high-pass area (min. # of pixels in contour area)"))
        self.lowPass_cb.setText(_translate("MainWindow", "Apply low-pass"))
        self.highPass_cb.setText(_translate("MainWindow", "Apply high-pass"))
        self.lowPass_le.setToolTip(_translate("MainWindow", "<html><head/><body><p>Before tracking, specify the lowpass contour area threshold for detection. All contours with areas greater than the specified threshold value will be discarded. Sometimes it is useful to track once with a low threshold value as a guess and then look at the tracking output to determine a better guess for a second pass through the tracking. Lowpass threshold pixel area defaults to 8000 pixels.</p></body></html>"))
        self.lowPass_le.setText(_translate("MainWindow", "8000"))
        self.medianSlider.setToolTip(_translate("MainWindow", "Choose of Median kernal"))
        self.gaussSlider.setToolTip(_translate("MainWindow", "Vary the size in pixels of the Gaussian Kernel."))
        self.label_2.setText(_translate("MainWindow", "low-pass area (max. # of pixels in contour area)"))
        self.trkTrack_B.setToolTip(_translate("MainWindow", "Starts object tracking on currently loaded video."))
        self.trkTrack_B.setText(_translate("MainWindow", "Track"))
        self.saveTrack_b.setText(_translate("MainWindow", "Save track"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Chose project path:"))
        self.chooseProjectPath_b.setToolTip(_translate("MainWindow", "Choose project path."))
        self.chooseProjectPath_b.setText(_translate("MainWindow", "Choose project path"))
        self.active_path_label.setText(_translate("MainWindow", "No path specified"))
        self.label_20.setText(_translate("MainWindow", "Active path:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Project"))
        self.groupBox.setTitle(_translate("MainWindow", "Video parameters:"))
        self.trkPreview_B.setToolTip(_translate("MainWindow", "Quickly preview video before tracking."))
        self.trkPreview_B.setText(_translate("MainWindow", "Fast Preview"))
        self.label_10.setText(_translate("MainWindow", "Video path:"))
        self.trkLoad_B.setToolTip(_translate("MainWindow", "Load video to be tracked."))
        self.trkLoad_B.setText(_translate("MainWindow", "Load Video"))
        self.pathLabel.setText(_translate("MainWindow", "No video loaded"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Video"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Background subtraction method:"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Chose and option:"))
        self.selBackgroundVid_b.setText(_translate("MainWindow", "Extract frame from video"))
        self.choose_background_b.setText(_translate("MainWindow", "Chose blank image"))
        self.firstFrame_rb.setText(_translate("MainWindow", "Use first frame as background"))
        self.specifyBackground_rb.setText(_translate("MainWindow", "Specify background image"))
        self.mog_rb.setText(_translate("MainWindow", "MOG background subtraction"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Detection"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Block-out regions:"))
        self.enableBlock_b.setText(_translate("MainWindow", "Enable"))
        self.blockOutRegions_cb.setText(_translate("MainWindow", "Block out regions"))
        self.disableBlock_b.setText(_translate("MainWindow", "Disable"))
        self.addBlock_b.setText(_translate("MainWindow", "Add"))
        self.deleteBlock_b.setText(_translate("MainWindow", "Delete"))
        self.saveBlock_b.setText(_translate("MainWindow", "Save"))
        self.loadBlock_b.setText(_translate("MainWindow", "Load"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Block-out regions"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Track control:"))
        self.label_8.setText(_translate("MainWindow", "Track between frames :"))
        self.selectStartStop_b.setToolTip(_translate("MainWindow", "Prompts user to select temporal range on selected video to be tracked."))
        self.selectStartStop_b.setText(_translate("MainWindow", "Select tracking start and stop frames"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Tracking limits"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tracking output:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tracking"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Post-processing"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Import 2D tracks for edit and reconstruction:"))
        self.reorder_b.setText(_translate("MainWindow", "Save reordered views"))
        self.deleteTrack_b.setText(_translate("MainWindow", "Delete track"))
        self.tracks_lw.setToolTip(_translate("MainWindow", "Selected item in list is the active file for post-processing. Make sure cameras appear in list in ascending order (i.e. first, second, third camera going upstream)."))
        self.show2Dplot_B.setText(_translate("MainWindow", "Show plot (select or change)"))
        self.loadTracks_b.setToolTip(_translate("MainWindow", "Select all file for post-processing a single trajectory."))
        self.loadTracks_b.setText(_translate("MainWindow", "Load tracks ..."))
        self.delAllTracks_b.setToolTip(_translate("MainWindow", "Unload all previously loaded tracks"))
        self.delAllTracks_b.setText(_translate("MainWindow", "Delete all tracks"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Edit 2D track -> "))
        self.ppBlank_B.setToolTip(_translate("MainWindow", "Removed erroneous data from selected rows in the table."))
        self.ppBlank_B.setText(_translate("MainWindow", "Blank selected rows on track "))
        self.interpolate_b.setText(_translate("MainWindow", "Interpolate blank rows"))
        self.ppUndo_B.setToolTip(_translate("MainWindow", "Reverts active track back to its orginal state."))
        self.ppUndo_B.setText(_translate("MainWindow", "Undo changes to active track"))
        self.saveTrackEdits_b.setText(_translate("MainWindow", "Save track as ..."))
        self.newCalibration_b.setText(_translate("MainWindow", "Create new calibration"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_4), _translate("MainWindow", "Create calibration"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Perform 3D reconstruction:"))
        self.loadCal_b.setText(_translate("MainWindow", "Load calibration file"))
        self.showCal_b.setText(_translate("MainWindow", "Show calibration in TableView"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_11), _translate("MainWindow", "Load Calibration"))
        self.reconstruct_3D_b.setText(_translate("MainWindow", "Reconstruct 3D"))
        self.save3DTrack_b.setText(_translate("MainWindow", "Save 3D track"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Plot controls:"))
        self.label_23.setText(_translate("MainWindow", "z"))
        self.label_17.setText(_translate("MainWindow", "x"))
        self.label_22.setText(_translate("MainWindow", "y"))
        self.label_27.setText(_translate("MainWindow", "max."))
        self.label_26.setText(_translate("MainWindow", "min."))
        self.label_3.setText(_translate("MainWindow", "Set axis limits:"))
        self.plot3D_b.setText(_translate("MainWindow", "Plot 3D track"))
        self.show3Dcoords_b.setText(_translate("MainWindow", "Show 3D coordinates"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_12), _translate("MainWindow", "Construct 3D track"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Table view:"))
        self.tableItem_l.setText(_translate("MainWindow", "Current item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Processing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

